TeenBiscuits/Pro2324

- README.md
> Actualizar README

- docs/pro.tree
- docs/topics/Bloque-1.md
- docs/topics/Teoria.topic
> Añadir teoría de Pro1 - Bloque 1

- docs/pro.tree
- docs/topics/Bloque-2.md
- docs/topics/Teoria.topic
Co-authored-by: TeenBiscuits <81629707+TeenBiscuits@users.noreply.github.com>
> Añadir teoría de Pro1 - Bloque 2

- docs/topics/Pro-1-Boletin-2.md
- docs/topics/Pro-1-Boletin-3-Sin-Enun.md
- docs/topics/Pro-1-Boletin-3.md
- docs/topics/Pro-1-Boletin-4-Sin-Enun.md
- docs/topics/Pro-1-Boletin-4.md
> Añadidos enunciados del Bol 2-3-4

- docs/cfg/buildprofiles.xml
- docs/topics/Pro2324.topic
- Añadidos nuevos enlaces a página de inicio
> Añadidos nuevos enlaces a página de inicio

- .github/pull_request_template.md
- docs/topics/Agradecimientos.md
- docs/topics/Boletines.topic
- Fuentes Boletines
- Fix typo Pull Request
> Fuente boletines

- README.md
- docs/pro.tree
- docs/topics/Algoritmos.md
- docs/topics/Bibliografia.md
- docs/topics/Extras.md
- docs/topics/Extras.topic
- docs/topics/Para-Colaboradores.md
- docs/topics/Pro2324.topic
- docs/topics/Teoria-Introduccion.md
- docs/topics/Teoria.topic
- docs/topics/Tres-En-Raya.md
- Últimos retoques para publicación
> Versión Lista Para Publicación

- .github/workflows/deploy.yml
- docs/cfg/buildprofiles.xml
- docs/topics/Para-Colaboradores.md
> Add Angolia Search

- docs/topics/Pro-1-Boletin-2.md
- Corregidos unos títulos del Boletín 2
> Corregidos unos títulos del Boletín 2

- docs/pro.tree
- docs/topics/Tema-2.md
- docs/topics/Teoria.topic
> T2 Gestión Dinámica de Memoria Punteros.

- docs/topics/Bloque-1.md
- docs/topics/Tema-2.md
> Mejora del Tema 2 TGR 29/02

- docs/pro.tree
- docs/topics/Tema-1.md
- docs/topics/Teoria.topic
- T1 Tipos Abstractos de Datos TAD
> T1 Tipos Abstractos de Datos TAD

- docs/pro.tree
- docs/topics/Agradecimientos.md
- docs/topics/Boletines.topic
- docs/topics/Extras.topic
- docs/topics/Para-Colaboradores.md
- docs/topics/Pro2324.topic
- docs/topics/Teoria.topic
- docs/topics/Tutoriales.topic
- Próximamente y Mejoras Varias
> Próximamente y Mejoras Varias

- docs/code/Boletin_4/Ejercicio_01.c
- docs/code/Boletin_4/Ejercicio_02.c
- docs/code/Boletin_4/Ejercicio_03.c
- docs/code/Boletin_4/Ejercicio_04.c
- docs/code/Boletin_4/Ejercicio_10.c
- docs/code/Boletin_4/Ejercicio_24.c
- docs/code/Boletin_4/Ejercicio_25.c
- docs/topics/02-Boletines/Pro-1/Boletin-4.md
- src/Boletin_4/Ejercicio_01.c
- src/Boletin_4/Ejercicio_02.c
- src/Boletin_4/Ejercicio_03.c
- src/Boletin_4/Ejercicio_04.c
- src/Boletin_4/Ejercicio_10.c
- src/Boletin_4/Ejercicio_24.c
- src/Boletin_4/Ejercicio_25.c
- Publicados los Ejercicios Nuevos del Boletín 4 #101
> Nuevos Ejercicios Pro 1 Bol 4

- docs/pro.tree
- Añadidas redirecciones de la página web para evitar crear enlaces rotos
> Añadidas redirecciones de la página web para evitar crear enlaces rotos

- .github/workflows/deploy.yml
- .github/workflows/tests.yml
- .idea/runConfigurations/Construir_Documentación__pro_.xml
- SECURITY.md
- docs/cfg/buildprofiles.xml
- docs/pro.tree
- docs/writerside.cfg
- Eliminada la versión de la documentación, provocaba un bug que generaba un `sitemap.xml` incorrecto.
> Eliminada versión documentación

- docs/cfg/buildprofiles.xml
- docs/cfg/gtag.js
- Añadidos Google Analytics
- Edit with GitHub
- Add og-image
> Modificaciones para mejorar el SEO

- docs/cfg/buildprofiles.xml
- docs/cfg/cookie-banner.html
- Creado Banner de Cookies y Políticas de Privacidad
> Creado Banner de Cookies y Políticas de Privacidad

- docs/code/Ejemplos/Tema_3/copyList.c
- docs/code/Ejemplos/Tema_3/createEmptyList.c
- docs/code/Ejemplos/Tema_3/deleteAtPosition.c
- docs/code/Ejemplos/Tema_3/deleteList.c
- docs/code/Ejemplos/Tema_3/findItem.c
- docs/code/Ejemplos/Tema_3/first.c
- docs/code/Ejemplos/Tema_3/getItem.c
- docs/code/Ejemplos/Tema_3/isEmptyList.c
- docs/code/Ejemplos/Tema_3/last.c
- docs/code/Ejemplos/Tema_3/next.c
- docs/code/Ejemplos/Tema_3/previous.c
- docs/code/Ejemplos/Tema_3/updateItem.c
- src/Ejemplos/Tema_3/copyList.c
- src/Ejemplos/Tema_3/createEmptyList.c
- src/Ejemplos/Tema_3/deleteAtPosition.c
- src/Ejemplos/Tema_3/deleteList.c
- src/Ejemplos/Tema_3/findItem.c
- src/Ejemplos/Tema_3/first.c
- src/Ejemplos/Tema_3/getItem.c
- src/Ejemplos/Tema_3/isEmptyList.c
- src/Ejemplos/Tema_3/last.c
- src/Ejemplos/Tema_3/next.c
- src/Ejemplos/Tema_3/previous.c
- src/Ejemplos/Tema_3/updateItem.c
- Las implementaciones del Tema 3 #118
> Añadidas Implementaciones Tema 3

- .idea/Pro2324.iml
- .idea/Pro23242.iml
- .idea/misc.xml
- .idea/modules.xml
- .idea/runConfigurations/Construir_Documentación.xml
- .idea/runConfigurations/Exportar_a_PDF.xml
- Reseteadas las configuraciones del IDEA
> Reset idea folder
